# Demographic Trends in Treatment Response to Pain Reprocessing Therapy for Chronic Lower Back Pain {#sec:org5437eb3}

(Note: if you are reading the PDF of this file from the git repository,
it may be out of date. It is included in the repo for convenience but
the canonical writeup is in the org file in the repo).

## Introduction {#sec:org3356f4c}

Chronic lower back pain (cLBP) is the leading cause of disability world
wide and, because of an aging population, the problem is getting worse
(Hartvigsen et al., 2018). Treatment practices in the United States in
particular have indicated a link between cLBP and the opiod epidemic
(Shipton et al., 2018). Ashar et al investigates the effectiveness of
pain reprocessing therapy (PRT) on cLBP and finds a non-trivial effect
(Ashar et al., 2022). In this writeup I analyze the demographic data
associated with that study and find some compelling correlations between
demographic variables and the effectiveness of both PRT and the open
placebo (Saline).

## Summary of Ashar et all 2022 Results {#sec:org04b11bc}

Subjects in the Ashar study were placed into one of three groups: Pain
Reprocessing Therapy, saline injection in the lower back, and standard
of care(Ashar et al., 2022). PRT consisted of one telehealth session and
8 sessions with PRT specialized therapists(Ashar et al., 2022). The
saline injection was an open placebo(Ashar et al., 2022). Patients were
tracked for 12 months after treatment to determine the long term
effectiveness of each intervention using a variety of standardized
questionaires covering cLBP symptoms and other pertinent
information(Ashar et al., 2022).

```{r child="derived_data/patient-count.fragment.Rmd"}
```

The results relevant to this analysis are succinctly summarized by
Figure [1](#fig:org91a3f3b){reference-type="ref"
reference="fig:org91a3f3b"}.

![PRT is effective at mitigating cLBP (compared to Saline and
SOC).](./figures/bpi_intensity_by_group.png){#fig:org91a3f3b
width=".9\\linewidth"}

The question examined in this analysis is how demographics interacts
with treatment.

## Demographic Data {#sec:org6be84ae}

Ashar and his colleagues made their data sets available to the public
(Ashar et al., 2021). The included demographic data includes information
about education, ethnicity, hispanic status, employment status,
exercise, handedness, self-reported socioeconomic status, marital
status, age, weight, gender, and backpain length.

These data constitute a mixed space of unordered discrete, ordered
discrete, and ordered continuous variables and thus do not lend
themselves to simple methods of dimensionality reduction. Nevertheless,
it is unlikely that the patient population fills this abstract space of
variability.

## Dimensionality Reduction of Demographic Data {#sec:org9bbfddb}

To understand whether there are clusters in the demographic data (as a
first step towards understanding the effects of demographic status
alongside the intervention studied here) we trained a variational
auto-encoder(Kingma and Welling, 2019) on this demographic data as a
method of dimensionality reduction. An auto-encoder is a simple neural
network which is charged with reproducing data placed on its input layer
at its output layer. The utility of such an exercise is that the middle
layer of such a network typically consists of a small number of neurons,
which forces the network to encode the input in a small number of
dimensions.

Variational Autoencoders use the inner layer to parameterize a
probability distribution, samples from which are then translated by the
second half of the network into the original output. This exercise
improves the smoothness of the representation of lower dimensional
representation of the data.

In this analysis our variational autoencoder was very simple: it had one
intermediate layer of dimension 3, an inner latent space with dimension
2, and a symmetric decoder (with the exception of a dropout layer on the
input of the encoder).

After training this network for 30,000 epochs we attained a
two-dimensional representation of the demographic data shown in Figure
[2](#fig:org9bfa563){reference-type="ref" reference="fig:org9bfa563"}.

![Two dimensional representation of patient demographics generated by a
variational autoencoder. A semi-supervised clustering is encoded via
point color.](./figures/demo-projection.png){#fig:org9bfa563
width=".9\\linewidth"}

A visual inspection of the two-dimensional representation of the data
suggests four clusters and a cloud of outliers. The outlier cloud was
identified by hand and the remaining clusters identified using spectral
clustering(Pedregosa et al., 2011).

## Automatic Cluster Meaning Identification {#sec:org46fc6a8}

A challenge associated with non-linear dimensionality reduction combined
with cluster analysis is the difficulty of associating meaning with each
cluster since the transformation to the lower dimensional space is not
easily interpreted.

There are several possible solutions to this problem, but here we
employed an unsupervised method: for each cluster, we trained a tree
based model (AdaBoost (Freund and Schapire, 1997)) to predict whether a
point would be classified into that cluster. From such a model we can
extract the variables which are most important for the classification
and then calculate summary statistics for each cluster. Using this
method we identified the four distinct clusters as:

-   Younger, Male, Unmarried, White

-   Older, Male, Married, White

-   Lower Weight, Female, Unmarried, White

-   Median Weight, Female, Married, White

A pat characterization of the diffuse outlier cloud is not furnished so
easily, but most of these data points are characterized by being
non-white participants.

## Effect of Cluster Membership on Treatment {#sec:orge4ab3d8}

Now that we have a plausible clustering of the subjects by demographic
character, it is natural to ask whether these demographic identities
correspond to treatment effect differences. This is show in Figure
[3](#fig:org3b2c225){reference-type="ref" reference="fig:org3b2c225"}.

![The effect of demographic cluster on the effectiveness of PRT and
Saline on
cLBP.](./figures/outcomes_by_demographic_clustering.png){#fig:org3b2c225
width=".9\\linewidth"}

The picture makes the case that there are strong effects of demographic
group on treatment effect. In particular, older, unmarried men (who are
white, like most participants) and younger, unmarried women (also white)
benefit the most from the treatment. Other demographic groups benefit
less from the intervention.

# References {#sec:org3bd7fee}

::: {#citeproc_bib_item_1}
Ashar, Y.K., Gordon, A., Schubiner, H., Uipi, C., Knight, K., Anderson,
Z., Carlisle, J., Polisky, L., Geuter, S., Flood, T.F., others (2021).
*[Pain reprocessing therapy for chronic back pain: A randomized
controlled trial with functional
neuroimaging](https://figshare.com/s/1840dc4c0e236a7072ca)*.
:::

::: {#citeproc_bib_item_2}
Ashar, Y.K., Gordon, A., Schubiner, H., Uipi, C., Knight, K., Anderson,
Z., Carlisle, J., Polisky, L., Geuter, S., Flood, T.F., others (2022).
Effect of pain reprocessing therapy vs placebo and usual care for
patients with chronic back pain: A randomized clinical trial. *Jama
Psychiatry* 79, 13--23.
:::

::: {#citeproc_bib_item_3}
Freund, Y., Schapire, R.E. (1997). A decision-theoretic generalization
of on-line learning and an application to boosting. *Journal of Computer
and System Sciences* 55, 119--139.
:::

::: {#citeproc_bib_item_4}
Hartvigsen, J., Hancock, M.J., Kongsted, A., Louw, Q., Ferreira, M.L.,
Genevay, S., Hoy, D., Karppinen, J., Pransky, G., Sieper, J., Smeets,
R.J., Underwood, M., Buchbinder, R., Hartvigsen, J., Cherkin, D.,
Foster, N.E., Maher, C.G., Underwood, M., van Tulder, M., Anema, J.R.,
Chou, R., Cohen, S.P., Costa, L.M., Croft, P., Ferreira, M., Ferreira,
P.H., Fritz, J.M., Genevay, S., Gross, D.P., Hancock, M.J., Hoy, D.,
Karppinen, J., Koes, B.W., Kongsted, A., Louw, Q., Öberg, B., Peul,
W.C., Pransky, G., Schoene, M., Sieper, J., Smeets, R.J., Turner, J.A.,
Woolf, A. (2018). [What low back pain is and why we need to pay
attention](https://doi.org/https://doi.org/10.1016/S0140-6736(18)30480-X).
*The Lancet* 391, 2356--2367.
:::

::: {#citeproc_bib_item_5}
Kingma, D.P., Welling, M. (2019). [An introduction to variational
autoencoders](https://doi.org/10.1561/2200000056). *Foundations and
Trends® in Machine Learning* 12, 307--392.
:::

::: {#citeproc_bib_item_6}
Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B.,
Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V.,
Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M.,
Duchesnay, E. (2011). Scikit-learn: Machine learning in Python. *Journal
of Machine Learning Research* 12, 2825--2830.
:::

::: {#citeproc_bib_item_7}
Shipton, E.A., Shipton, E.E., Shipton, A.J. (2018). [A review of the
opioid epidemic: What do we do about
it?](https://doi.org/10.1007/s40122-018-0096-7) *Pain and Therapy* 7,
23--36.
:::
